- s1
- - '1'
  - - M2
    - n
  - - M1
    - n
- - -1*q^2
  - - M1
    - n
  - - M2
    - n
- - ''
  - ''
  - ''
---
- s2
- - '1'
  - - M3
    - n
  - - M1
    - n
- - -1*q
  - - M1
    - n
  - - M3
    - n
- - -1*(q+1)
  - - M2
    - n
  - ''
---
- s3
- - '1'
  - - M4
    - n
  - - M1
    - n
- - '-1'
  - - M1
    - n
  - - M4
    - n
- - '-1'
  - - M3
    - n
  - ''
---
- s4
- - '1'
  - - M3
    - n
  - - M2
    - n
- - -1*q^2
  - - M2
    - n
  - - M3
    - n
- - ''
  - ''
  - ''
---
- s5
- - '1'
  - - M4
    - n
  - - M2
    - n
- - -1*q^2
  - - M2
    - n
  - - M4
    - n
- - -1*\frac{q-1}{q^{-1}+1}
  - - M3
    - n
  - - M3
    - n
---
- s6
- - '1'
  - - M4
    - n
  - - M3
    - n
- - -1*q^2
  - - M3
    - n
  - - M4
    - n
- - ''
  - ''
  - ''
---
- s7
- - '1'
  - - M1
    - n
  - - M1
    - m
- - -1*v^{2(-1)^{n-m}}
  - - M1
    - m
  - - M1
    - n
- - ''
  - ''
  - ''
---
- s8
- - '1'
  - - M2
    - n
  - - M1
    - m
- - -1*v^{2(-1)^{n-m}}
  - - M1
    - m
  - - M2
    - n
- - ''
  - ''
  - ''
---
- s9
- - '1'
  - - M3
    - n
  - - M1
    - m
- - '-1'
  - - M1
    - m
  - - M3
    - n
- - ''
  - ''
  - ''
---
- s10
- - '1'
  - - M4
    - n
  - - M1
    - m
- - -1*v^{2(-1)^{n-m}+1}
  - - M1
    - m
  - - M4
    - n
- - ''
  - ''
  - ''
---
- s11
- - '1'
  - - M1
    - n
  - - M2
    - m
- - -1*v^2{(-1)^{n-m}}
  - - M2
    - m
  - - M1
    - n
- - ''
  - ''
  - ''
---
- s12
- - '1'
  - - M2
    - n
  - - M2
    - m
- - -1*v^{4(-1)^{n-m}}
  - - M2
    - m
  - - M2
    - n
- - ''
  - ''
  - ''
---
- s13
- - '1'
  - - M3
    - n
  - - M2
    - m
- - -1*v^{2(-1)^{n-m}}
  - - M2
    - m
  - - M3
    - n
- - ''
  - ''
  - ''
---
- s14
- - '1'
  - - M4
    - n
  - - M2
    - m
- - '-1'
  - - M2
    - m
  - - M4
    - n
- - ''
  - ''
  - ''
---
- s15
- - '1'
  - - M1
    - n
  - - M3
    - m
- - '-1'
  - - M3
    - m
  - - M1
    - n
- - ''
  - ''
  - ''
---
- s16
- - '1'
  - - M2
    - n
  - - M3
    - m
- - -1*v^{2(-1)^{n-m}}
  - - M3
    - m
  - - M2
    - n
- - ''
  - ''
  - ''
---
- s17
- - '1'
  - - M3
    - n
  - - M3
    - m
- - -1*v^{2(-1)^{n-m}}
  - - M3
    - m
  - - M3
    - n
- - ''
  - ''
  - ''
---
- s18
- - '1'
  - - M4
    - n
  - - M3
    - m
- - -1*v^{2(-1)^{n-m}}
  - - M3
    - m
  - - M4
    - n
- - ''
  - ''
  - ''
---
- s19
- - '1'
  - - M1
    - n
  - - M4
    - m
- - -1*v^{2(-1)^{n-m+1}}
  - - M4
    - m
  - - M1
    - n
- - ''
  - ''
  - ''
---
- s20
- - '1'
  - - M2
    - n
  - - M4
    - m
- - '-1'
  - - M4
    - m
  - - M2
    - n
- - ''
  - ''
  - ''
---
- s21
- - '1'
  - - M3
    - n
  - - M4
    - m
- - -1*v^{2(-1)^{n-m+1}}
  - - M4
    - m
  - - M3
    - n
- - ''
  - ''
  - ''
---
- s22
- - '1'
  - - M4
    - n
  - - M4
    - m
- - -1*v^{4(-1)^{n-m}}
  - - M4
    - m
  - - M4
    - n
- - ''
  - ''
  - ''
---
- t1
- - '1'
  - - M1
    - n
  - - K_1
    - n
- - -1*v^{2(-1)^{n}}
  - - K_1
    - n
  - - M1
    - n
- - ''
  - ''
  - ''
---
- t2
- - '1'
  - - M2
    - n
  - - K_1
    - n
- - -1*v^{2(-1)^{n}}
  - - K_1
    - n
  - - M2
    - n
- - ''
  - ''
  - ''
---
- t3
- - '1'
  - - M3
    - n
  - - K_1
    - n
- - '-1'
  - - K_1
    - n
  - - M3
    - n
- - ''
  - ''
  - ''
---
- t4
- - '1'
  - - M4
    - n
  - - K_1
    - n
- - -1*v^{2(-1)^{n+1}}
  - - K_1
    - n
  - - M4
    - n
- - ''
  - ''
  - ''
---
- t5
- - '1'
  - - M1
    - n
  - - K_2
    - n
- - -1*v^{2(-1)^{n}}
  - - K_2
    - n
  - - M1
    - n
- - ''
  - ''
  - ''
---
- t6
- - '1'
  - - M2
    - n
  - - K_2
    - n
- - -1*v^{4(-1)^{n}}
  - - K_2
    - n
  - - M2
    - n
- - ''
  - ''
  - ''
---
- t7
- - '1'
  - - M3
    - n
  - - K_2
    - n
- - -1*v^{2(-1)^{n}}
  - - K_2
    - n
  - - M3
    - n
- - ''
  - ''
  - ''
---
- t8
- - '1'
  - - M4
    - n
  - - K_2
    - n
- - '-1'
  - - K_2
    - n
  - - M4
    - n
- - ''
  - ''
  - ''
---
- s23
- - '1'
  - - M1
    - n
  - - M1
    - n+1
- - -1*v^{-2}
  - - M1
    - n+1
  - - M1
    - n
- - -1*\frac{1}{v^2-1}
  - ''
  - ''
---
- s24
- - '1'
  - - M2
    - n
  - - M1
    - n+1
- - -1*v^{-4}
  - - M1
    - n+1
  - - M2
    - n
- - -1*v^{-2}
  - - M3
    - n
  - ''
---
- s25
- - '1'
  - - M3
    - n
  - - M1
    - n+1
- - -1*v^{-1}
  - - M1
    - n+1
  - - M3
    - n
- - -1*v^{-1}*(v^2+1)
  - - M4
    - n
  - ''
---
- s26
- - '1'
  - - M4
    - n
  - - M1
    - n+1
- - -1*v^2
  - - M1
    - n+1
  - - M4
    - n
- - ''
  - ''
  - ''
---
- s27
- - '1'
  - - M1
    - n
  - - M2
    - n+1
- - '-1'
  - - M2
    - n+1
  - - M1
    - n
- - ''
  - ''
  - ''
---
- s28
- - '1'
  - - M2
    - n
  - - M2
    - n+1
- - -1*v^{-4}
  - - M2
    - n+1
  - - M2
    - n
- - -1*\frac{1}{v^4-1}
  - ''
  - ''
---
- s29
- - '1'
  - - M3
    - n
  - - M2
    - n+1
- - -1*v^{-2}
  - - M2
    - n+1
  - - M3
    - n
- - -1*v^{-2}
  - - M1
    - n+1
  - ''
---
- s30
- - '1'
  - - M4
    - n
  - - M2
    - n+1
- - '-1'
  - - M2
    - n+1
  - - M4
    - n
- - -1*\frac{v^2-1}{v^2+1}
  - - M1
    - n+1
  - - M1
    - n+1
---
- s31
- - '1'
  - - M1
    - n
  - - M3
    - n+1
- - -1*v^2
  - - M3
    - n+1
  - - M1
    - n
- - ''
  - ''
  - ''
---
- s32
- - '1'
  - - M2
    - n
  - - M3
    - n+1
- - '-1'
  - - M3
    - n+1
  - - M2
    - n
- - ''
  - ''
  - ''
---
- s33
- - '1'
  - - M3
    - n
  - - M3
    - n+1
- - -1*v^{-2}
  - - M3
    - n+1
  - - M3
    - n
- - -1*\frac{1}{v^2-1}
  - ''
  - ''
---
- s34
- - '1'
  - - M4
    - n
  - - M3
    - n+1
- - -1*v^{-2}
  - - M3
    - n+1
  - - M4
    - n
- - -1*v^{-2}
  - - M1
    - n+1
  - ''
---
- s35
- - '1'
  - - M1
    - n
  - - M4
    - n+1
- - -1*v^4
  - - M4
    - n+1
  - - M1
    - n
- - ''
  - ''
  - ''
---
- s36
- - '1'
  - - M2
    - n
  - - M4
    - n+1
- - -1*v^4
  - - M4
    - n+1
  - - M2
    - n
- - ''
  - ''
  - ''
---
- s37
- - '1'
  - - M3
    - n
  - - M4
    - n+1
- - '-1'
  - - M4
    - n+1
  - - M3
    - n
- - ''
  - ''
  - ''
---
- s38
- - '1'
  - - M4
    - n
  - - M4
    - n+1
- - -1*v^4
  - - M4
    - n+1
  - - M4
    - n
- - -1*\frac{1}{v^4-1}
  - ''
  - ''
